### ISSUE TITLE
DSM US AND DSM UK MERGE

### ISSUE THREAD

**Issue by nzp15** [doprdele/pidpid#1]
Just merge both of these.... No point in having them separate 
1. There are 4 DSM e-shops and the PID's are all getting mixed 
2. It is more confusing to cross reference the two since Pid's are getting mixed
3. saves you resources if you merge since you would only be running one scraper

**Comment by doprdele** [comment]
@nzp15 I'll try to make these changes by the end of next week. The problem is that in the ElasticSearch index the primary ID is by product id. In the future, the primary ID will need to be random since the same ID could appear in different countries, however there will still be a pid and timestamp field, so it will be OK

**Comment by doprdele** [comment]
The new scraper is in testing currently.

**Comment by doprdele** [comment]
All fixed @nzp15
